UserReactivated: Användare återaktiverad
UserUnknown: Användare obekant
UserOrArticleUnknown: Användare eller föremål obekant
PurchaseSuccess: Skål!
PurchaseDebtful: Obs: Tillgodo är i et negativa området!
NotEnoughItems: Inte nog föremål tillgänglig
ErrorOccured: Någonting gjorde fel
ItemUnknown: Förenåd obekant
PurchaseSuccessCash price@Int currency@Text: Skål. Betala #{currency} #{formatIntCurrency price} #{currency} kontant tack.
ItemDisappeared: Föremål försvann o_0
Amount: Mängd
