UserReactivated: Användare återaktiverad
UserUnknown: Användare obekant
UserOrArticleUnknown: Användare eller föremål obekant
PurchaseSuccess: Skål!
PurchaseDebtful: Obs: Tillgodo är i et negativa området!
NotEnoughItems: Inte nog föremål tillgänglig
ErrorOccured: Någonting gjorde fel
ItemUnknown: Förenåd obekant
PurchaseSuccessCash price@Int currency@Text: Skål. Betala #{currency} #{formatIntCurrency price} #{currency} kontant tack.
ItemDisappeared: Föremål försvann o_0
Amount: Mängd
EditSuccess: Editering lyckad
EditFail: Editering inte möjlig
Name: Namn
Price: Pris
CurrentStock: Aktuellt bestånd
AnnouncedStock: Meddeladt bestånd
DeleteItem: Radera föremål
ItemDeleted: Föremål raderad
UserCreated: Skapade användare
UserNotCreated: Användaren kunde inte skappas
EmailNotify: Inträd en E-Mail-adress om du vill få meddelanden
BuyNotification: Meddela köpar
UserEdited: Användaredatan editerades
UserNotEdited: Editering av användaredatan misslyckades
Payout desc@Text: Utbetalning: #{desc}
PaidOut: Belopp utbetalades
NotPaidOut: Utbetalning inte möjlig
Value: Belopp
Description: Beskrivning
StockedUp: Beståndet fylldes
NotStockedUp: Beståndet kann inte fyllas negativt
StockupError: Fel medan fyllningen
AmountAdded: Tillagd mängd
ItemAdded: Nytt föremål tillades
ItemNotAdded: Fel vid tillägg av föremålet
AmountWarning: Varning med mängd
Recharged: Saldoomladdning lyckad!
RechargeError: Fel vid Omladdning av Saldo
CashCheck: Kassarevision
CashChecked: Kassarevisionen utfördes. Kassa uppdaterade.
CashCheckError: Fel vid kassarevision

Submit: Insända
Home: Hemsida

SelectAvatar: Välja avatarn
